declare module '@mui/material/styles' {
  interface Palette {
    customColors: {
      dark: string
      main: string
      light: string
      bodyBg: string
      darkBg: string
      lightBg: string
      trackBg: string
      avatarBg: string
      tooltipBg: string
      tableHeaderBg: string
      primaryLighter: string
      primaryLightest: string
      secondaryLighter: string
      title: string
      inactive: string
      disable: string
      label: string
      mainText: string
      text1: string
      text2: string
      text3: string
      text4: string
      text5: string
      text6: string
      text7: string
      surfaeLighter: string
      chipWarningText: string
      textLabel: string
      chipBorder: string
      disabled: string
      disableBorder: string
      chipHoverBackground: string
      chipTonalBackground: string
      dividerColor: string
      badgeColorDefault: string
      sliderMainColor: string
      sliderSecColor: string
      sliderLabelColor: string
      sliderLabelTextColor: string
      datepickerText: string
      primarySuperLight: string
      menuItemTextColor: string
      surfaeLighterTwo: string
      chipPendingContainer: string
      chipPendingText: string
      chipWarningContainer: string
      extraTextColor: string
      customChipColor: string
      customChipBackgroundColor: string
      customChipSuccessBgColor: string
      musterdYellow: string
      blue400: string
      dashboardPurple: string
      AccentOn2: string
      stepDefault: string
      musterdYellowLight: string
      musterdYellowDark: string
      surface1: string
      exceptionOneBackground: string
      exceptionOneText: string
      exceptionTwoBackground: string
      exceptionTwoText: string
      tableHeader: string
      approvalPrimaryChipBG: string
      approvalPrimaryChipText: string
      surface2: string
      cardSurface1: string
    }
  }
  interface PaletteOptions {
    customColors?: {
      dark?: string
      main?: string
      light?: string
      bodyBg?: string
      darkBg?: string
      lightBg?: string
      trackBg?: string
      avatarBg?: string
      tooltipBg?: string
      tableHeaderBg?: string
      primaryLighter?: string
      primaryLightest?: string
      secondaryLighter?: string
      title?: string
      inactive?: string
      disable?: string
      label?: string
      mainText?: string
      text1?: string
      text2?: string
      text3?: string
      text4?: string
      text5?: string
      text6?: string
      text7?: string
      surfaeLighter?: string
      chipWarningText?: string
      textLabel?: string
      chipBorder?: string
      disabled?: string
      disableBorder?: string
      chipHoverBackground?: string
      chipTonalBackground?: string
      dividerColor?: string
      badgeColorDefault?: string
      sliderMainColor?: string
      sliderSecColor?: string
      sliderLabelColor?: string
      sliderLabelTextColor?: string
      datepickerText?: string
      primarySuperLight?: string
      menuItemTextColor?: string
      surfaeLighterTwo?: string
      chipPendingContainer?: string
      chipPendingText?: string
      chipWarningContainer?: string
      extraTextColor?: string
      customChipColor?: string
      customChipBackgroundColor?: string
      customChipSuccessBgColor?: string
      musterdYellow?: string
      musterdYellowLight?: string
      musterdYellowDark?: string
      blue400?: string
      dashboardPurple?: string
      AccentOn2?: string
      stepDefault?: string
      surface1?: string
      exceptionOneBackground?: string
      exceptionOneText?: string
      exceptionTwoBackground?: string
      exceptionTwoText?: string
      tableHeader?: string
      approvalPrimaryChipBG?: string
      approvalPrimaryChipText?: string
      surface2?: string
      cardSurface1?: string
    }
  }
}

export {}
